name: 'supply_chain_digital_twin'
version: '1.0.0'
config-version: 2

profile: 'supply_chain_profile'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  supply_chain_digital_twin:
    staging:
      +schema: silver
      +materialized: view
    marts:
      +schema: gold
      +materialized: table
